# --- Script to Generate Multiple AL Entities using ALTPGen based on Dataverse Entities---
# This script processes multiple entities in batch mode by calling Generate-Entity.ps1 for each entity
# To Update the Autogenerated Comment Block Below, import the latest Solution.xml from the dataverse Solution
# and use Copilot agent with the following prompt:
# "update the entities on the file Generate-Entity-List based on the file Solution.xml using all the
# rootcomponents with type 1 and update the BaseId to avoid ID overlapping. Do not update the BaseID
# of the current entities defined on the script"

# ============================================================================
# CONFIGURATION: ENTITY LIST
# ============================================================================
# Define the Dataverse entities to generate and their corresponding BC Table IDs
# ID Range from app.json: Check your project's idRanges configuration
# Each entity is assigned a unique BaseId to avoid conflicts
# Format: @{Entity = 'dataverse_entity_schemaname'; BaseId = 70XXX }
# ============================================================================

$entities = @(
    @{Entity = 'account'; BaseId = 50000 },
    @{Entity = 'quote'; BaseId = 50001 },
    @{Entity = 'quotedetail'; BaseId = 50002 },
    @{Entity = 'salesorder'; BaseId = 50003 },
    @{Entity = 'salesorderdetail'; BaseId = 50004 },
    @{Entity = 'transactioncurrency'; BaseId = 50005 }
);

# ============================================================================
# CONFIGURATION: OBJECT PREFIX
# ============================================================================
# TYPE: Configuration (project naming convention)
# PURPOSE: Prefix added to all generated AL object files for consistency
# COMMON VALUES:
#   "CDS"    = Common Data Service
#   "CRM"    = Customer Relationship Management
#   Custom prefix based on your project naming convention
# EXAMPLE: prefix="BCS", entity="account" → intermediate="CDSaccount.Table.al" → final="BCSCDSAccount.Table.al"
# ⚠️ UPDATE THIS: Set to your project's naming convention prefix
# ============================================================================

$objectPrefix = "BCS"

# --- Get Script Location ---
$SkillPath = $PSScriptRoot
$BasePath = Split-Path (Split-Path (Split-Path $SkillPath -Parent) -Parent) -Parent

# --- Process Each Entity ---
foreach ($item in $entities) {
    Write-Host "Processing $($item.Entity) with BaseId $($item.BaseId)" -ForegroundColor Cyan;
    
    # Set location to the scripts folder where Generate-Entity.ps1 is located
    Set-Location $PSScriptRoot;
    
    # Call Generate-Entity.ps1 for the current entity
    & ".\Generate-Entity.ps1" -Entity $item.Entity -BaseId $item.BaseId;
    
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Failed to generate entity: $($item.Entity)"
        exit 1
    }
}

# --- Post-Processing: Move and Rename Generated Files ---
# This section moves all generated .al files from the project root to the src/Table folder
# and adds the custom prefix defined in $objectPrefix variable
$sourcePath = $BasePath
$destinationPath = Join-Path $BasePath "src\Table"

# Ensure destination directory exists
if (-not (Test-Path $destinationPath)) {
    New-Item -ItemType Directory -Path $destinationPath -Force
    Write-Host "Created destination directory: $destinationPath" -ForegroundColor Yellow
}

# Get all .al files in the source directory (excluding those already in src/)
# This moves generated files from project root to proper table folder with prefix
Get-ChildItem -Path $sourcePath -Filter "*.al" -File | 
    Where-Object { $_.DirectoryName -eq $sourcePath } |
    ForEach-Object {
        Write-Host "Processing generated file: $($_.Name)" -ForegroundColor Cyan
        
        # Read file content
        $content = Get-Content $_.FullName -Raw
        
        # Update table name: "CDS entityname" → "BCS CDS Entityname"
        # Captures table ID and entity name, adds BCS prefix
        if ($content -match 'table\s+(\d+)\s+"CDS\s+([^"]+)"') {
            $tableId = $matches[1]
            $entityName = $matches[2]
            $newTableName = "BCS CDS $entityName"
            $content = $content -replace 'table\s+\d+\s+"CDS\s+[^"]+"', "table $tableId `"$newTableName`""
            Set-Content $_.FullName $content
            Write-Host "  Updated table name to: $newTableName" -ForegroundColor Green
        }
        
        # Apply the configured prefix to the filename
        # CDS*.Table.al → BCSCDS*.Table.al
        $newFileName = $objectPrefix + $_.Name
        $newPath = Join-Path $destinationPath $newFileName
        
        Write-Host "  Moving to: src\Table\$newFileName" -ForegroundColor Cyan
        Move-Item -Path $_.FullName -Destination $newPath -Force
        Write-Host "  Completed ✅" -ForegroundColor Green
    }

Write-Host ""
Write-Host "Batch generation complete!" -ForegroundColor Green
Write-Host "Generated files are in: $destinationPath" -ForegroundColor White
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Review generated tables in src/Table/" -ForegroundColor White
Write-Host "2. Update permission set (AGENTDEMO.permissionset.al)" -ForegroundColor White
Write-Host "3. Build project to verify" -ForegroundColor White

# --- How to Run This Script ---
# 1. Open PowerShell
# 2. Navigate to the skill scripts folder:
#    cd .github\skills\bc-dataverse-entity-generator\scripts
# 3. Execute the script:
#    .\Generate-Entity-List.ps1
#
# Prerequisites:
# - Generate-Entity.ps1 must be configured with correct Dataverse credentials
# - Azure AD App Registration must be set up with proper permissions
# - ALTPGen tool path must be valid in Generate-Entity.ps1
# - User must have read access to Dataverse environment
